<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.lattice-hub</groupId><artifactId>pole-java-adapters</artifactId><version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>pole-spring-boot-2</artifactId>
    <name>Pole Spring Boot 2 Adapter</name>
    <dependencies>
        <dependency><groupId>${project.groupId}</groupId><artifactId>pole-spring-common</artifactId></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-autoconfigure</artifactId><version>${spring.boot2.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.springframework</groupId><artifactId>spring-web</artifactId><version>5.3.31</version><scope>provided</scope></dependency>
        <dependency><groupId>javax.servlet</groupId><artifactId>javax.servlet-api</artifactId><version>4.0.1</version><scope>provided</scope></dependency>
        <dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-commons</artifactId><version>${spring.cloud2.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.springframework</groupId><artifactId>spring-webflux</artifactId><version>5.3.31</version><scope>provided</scope></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-test</artifactId><version>${spring.boot2.version}</version><scope>test</scope></dependency>
        <dependency><groupId>org.assertj</groupId><artifactId>assertj-core</artifactId><version>${assertj.version}</version><scope>test</scope></dependency>
        <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><version>${junit.version}</version><scope>test</scope></dependency>
    </dependencies>
</project>
