package io.github.latticehub.client;

public enum TrafficContextDiagnostic {
    MISSING_VERSION,
    DUPLICATE_VERSION,
    DUPLICATE_CAMPAIGN,
    DUPLICATE_LANE,
    DUPLICATE_BUCKET,
    UNSUPPORTED_VERSION,
    INVALID_BUCKET,
    NON_CANONICAL_VALUE,
    LABEL_TOO_LARGE,
    INVALID_UTF8,
    EMPTY_LABEL,
    SURROUNDING_WHITESPACE,
    CONTROL_CHARACTER,
    UNKNOWN_RESERVED_MEMBER,
    RESERVED_MEMBER_PROPERTIES,
    INVALID_BAGGAGE,
    TOO_MANY_MEMBERS,
    BAGGAGE_TOO_LARGE
}
